% Default listings data (your original example)
listings = struct(...
    'ItemName', {'Hermes Handbag', 'Vertu Ironflip'}, ...
    'Price', {4200, 3000}, ...
    'Condition', {'Used', 'New'}, ...
    'Location', {'Toronto', 'North York'}, ...
    'UserName', {'Alice', 'Bob'}, ...
    'Verified', {'Yes', 'No'}, ...
    'Category', {'Fashion & Accessories', 'Electronics & Gadgets'} ...
);

% New userinfo struct (expanded with all fields)
userinfo = struct(...
    'name', {}, ...
    'lastname', {}, ...
    'email', {}, ...
    'username', {}, ...
    'password', {}, ...
    'policyAgreed', {} ...
);

% Save to listings.mat (preserve listings, update userinfo)
save('listings.mat', 'listings', 'userinfo', '-v7.3');
